fr:
  githug: 
    cli:
      tasks:
        play: Initialiser le jeu
        test: Tester un niveau depuis un chemin de fichier
        hint: Obtenir un indice pour le niveau actuel
        reset: Redémarrer le niveau actuel

      reset:
        resetting: Redémarrage du niveau
        does_not_exist: Niveau n'existe pas

      make_directory:
        change_dir: Merci de passer dans le dossier git_hug
        no_dir_found: Aucun dossier githug trouvé, voulez-vous en créer un ?
        exiting: Fermeture

    game:
      play_level:
        welcome: Bienvenue sur Githug
        success: Félicitations, vous avez résolu ce niveau
        failure: "Désolé, cette solution n'est pas tout à fait juste !"
        hint_prompt: N'oubliez pas que vous pouvez taper `githug hint` pour un indice et `githug reset` pour redémarrer le niveau actuel

      test_level:
        valid: Solution valide
        invalid: Solution invalide

    level:
      level: "Niveau :"
      difficulty: "Difficulté :"
      no_hints: Aucun indice disponible pour ce niveau





